/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xsor_io_occlusion_NativeClass */

#ifndef _Included_xsor_io_occlusion_NativeClass
#define _Included_xsor_io_occlusion_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xsor_io_occlusion_NativeClass
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xsor_io_occlusion_NativeClass_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
